# === 선택지 랜덤화를 위한 설정값 ===
import random

# 재활 데이터 관리
id_train_index = 0
id_train_size = 0
id_train_scene_list = []

# 현재 사용 중인 "향 리스트"(정답/오답 풀에 함께 사용)
SCENT_POOL = [
    '장미','초콜릿','생강','멜론','소나무','화장품',
    '녹차','홍삼','복숭아','재/연기','박하','비누'
]

# 장면들에 이미 쓰고 있는 일반 오답(이미지 리소스가 있는 것만 넣으세요)
EXTRA_DISTRACTORS = [
    '잔디','케챱','양파','가죽','페인트','수박','당근','땅콩',
    '꿀','허브','고구마','로즈마리','쑥','유칼립투스','사과','오렌지',
    '포도','숯불고기','마늘','핫초코','신문지','계란','레몬','딸기'
]

# 필요 시 표시 텍스트 ↔ 이미지 키 매핑(파일명이 다를 때만 추가)
ASSET_KEY_MAP = {
    # '재/연기': '재연기',
    # '화장품': '파우더',
    # '귤(오렌지/감귤)': '오렌지',
    '유칼립투스': '허브',
}

def _asset_key(label: str) -> str:
    return ASSET_KEY_MAP.get(label, label)


def randomize_scent_choice_step(step: dict, *, use_extra_decoys=True, seed=None):
    """
    발향(scent>0) + choice_3/choice_4 스텝을 3지선다로 랜덤화.
    step['answer_text'] 가 있으면 그걸 정답으로, 없으면 SCENT_POOL에서 scent번호로 추정(권장X).
    """
    lt = step.get('layout_type', '')
    if step.get('scent', 0) <= 0:
        return
    if lt not in ('choice_3', 'choice_4'):
        return

    # 1) 정답 텍스트
    correct = step.get('answer_text')
    if not correct:
        # fallback: scent → SCENT_POOL (1-based 가정). 정확히 맞추려면 answer_text를 넣으세요.
        idx = step['scent'] - 1
        if 0 <= idx < len(SCENT_POOL):
            correct = SCENT_POOL[idx]
        else:
            return  # 정답 추정 불가

    # 2) 오답 풀
    pool = SCENT_POOL + (EXTRA_DISTRACTORS if use_extra_decoys else [])
    # 중복 제거 + 정답 우선 보장
    seen = set()
    pool = [x for x in pool if (x not in seen) and not seen.add(x)]
    # 정답 제외
    candidates = [p for p in pool if p != correct]
    if len(candidates) < 2:
        return

    # 3) 오답 2개 랜덤
    rnd = random.Random(seed if seed is not None else hash((step.get('sound'), step.get('head_title'), step.get('scent'))))
    distractors = rnd.sample(candidates, 2)

    # 4) 정답+오답 섞기
    choices = [correct] + distractors
    rnd.shuffle(choices)

    # 5) 할당(3지선다 강제)
    step['layout_type'] = 'choice_3'
    for i, txt in enumerate(choices, start=1):
        step[f'label_select_{i}'] = txt
        step[f'img_btn{i}'] = _asset_key(txt)
    # 4번은 비우기(렌더러가 그리지 않지만 깔끔하게)
    step['label_select_4'] = ''
    step['img_btn4'] = ''

# 재활 콘텐츠
id_train_scene_1 = [{'layout_type':'choice_0',
               'img_bg':'bg_s_01_01',
               'img_btn1':'잔디',
               'img_btn2':'케챱',
               'img_btn3':'장미',
               'img_btn4':'양파',
               'head_title':'Farm',
               'body_text':'멋진 정원이 있습니다.\n정원이 아름다워지기 위해 필요한 것이 있습니다.',
               'label_select_1':'잔디',
               'label_select_2':'케챱',
               'label_select_3':'장미',
               'label_select_4':'양파',
               'sound':'train_id_01_01',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)
                   
               {'layout_type':'choice_3',
               'img_bg':'bg_s_01_02',
               'img_btn1':'잔디',
               'img_btn2':'케챱',
               'img_btn3':'장미',
               'img_btn4':'양파',
               'head_title':'Farm',
               'body_text':'향을 느껴보시고 짐작해보세요.\n어떤 향을 느끼셨습니까?',
               'label_select_1':'잔디',
               'label_select_2':'케챱',
               'label_select_3':'장미',
               'label_select_4':'양파',
               'sound':'train_id_01_02',
               'answer_text':'장미',
               'scent':1},
               
               {'layout_type':'choice_0',
               'img_bg':'bg_s_01_03',
               'img_btn1':'돈2000',
               'img_btn2':'돈10000',
               'img_btn3':'돈20000',
               'img_btn4':'양파',
               'head_title':'Farm',
               'body_text':'장미 꽃다발을 주고받은 경험이 있으십니까?\n경험을 서로 나눠보세요.',
               'label_select_1':'2,800원',
               'label_select_2':'14,000원',
               'label_select_3':'28,000원',
               'label_select_4':'',
               'sound':'train_id_01_03',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)},
               
               {'layout_type':'choice_0',
               'img_bg':'bg_s_01_04',
               'img_btn1':'돈2000',
               'img_btn2':'돈10000',
               'img_btn3':'돈20000',
               'img_btn4':'양파',
               'head_title':'Farm',
               'body_text':'장미꽃 20송이를 가지고,\n꽃다발을 만들었습니다.',
               'label_select_1':'2,800원',
               'label_select_2':'14,000원',
               'label_select_3':'28,000원',
               'label_select_4':'',
               'sound':'train_id_01_04',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)},
               
               {'layout_type':'choice_3',
               'img_bg':'bg_s_01_04',
               'img_btn1':'돈2000',
               'img_btn2':'돈10000',
               'img_btn3':'돈20000',
               'img_btn4':'양파',
               'head_title':'Farm',
               'body_text':'장미 1송이가 1,400원이라면,\n금액이 얼마 필요할까요?',
               'label_select_1':'2,800원',
               'label_select_2':'14,000원',
               'label_select_3':'28,000원',
               'label_select_4':'버4',
               'sound':'train_id_01_05',
               'scent':0},
               
               {'layout_type':'choice_1',
               'img_bg':'bg_s_01_04',
               'img_btn1':'돈20000',
               'img_btn2':'돈20000',
               'img_btn3':'돈20000',
               'img_btn4':'돈20000',
               'head_title':'Farm',
               'body_text':'수고하셨습니다.\n감사합니다.',
               'label_select_1':'28,000원',
               'label_select_2':'28,000원',
               'label_select_3':'28,000원',
               'label_select_4':'28,000원',
               'sound':'train_id_thanks',
               'scent':0},
]
    
id_train_scene_2 = [{'layout_type':'choice_0',
               'img_bg':'bg_s_02_01',
               'img_btn1':'가죽',
               'img_btn2':'페인트',
               'img_btn3':'계피',
               'img_btn4':'레몬',
               'head_title':'Farm',
               'body_text':'시원한 음료를 만들고 있습니다.\n그런데 상큼한 재료가 없는 것 같습니다.',
               'label_select_1':'가죽',
               'label_select_2':'페인트',
               'label_select_3':'계피',
               'label_select_4':'레몬',
               'sound':'train_id_02_01',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)
               
               {'layout_type':'choice_3',
               'img_bg':'bg_s_02_01',
               'img_btn1':'가죽',
               'img_btn2':'페인트',
               'img_btn3':'계피',
               'img_btn4':'레몬',
               'head_title':'Farm',
               'body_text':'향을 느껴보시고 짐작해보세요.\n어떤 향을 느끼셨습니까?',
               'label_select_1':'가죽',
               'label_select_2':'페인트',
               'label_select_3':'계피',
               'label_select_4':'레몬',
               'sound':'train_id_02_02',
               'answer_text':'레몬',   
               'scent':2},

               {'layout_type':'choice_0',
               'img_bg':'bg_s_02_02',
               'img_btn1':'가죽',
               'img_btn2':'페인트',
               'img_btn3':'계피',
               'img_btn4':'레몬',
               'head_title':'Farm',
               'body_text':'레몬은 건강에 좋은 음식입니다.\n레몬의 효능에 대해 서로 나눠보세요.',
               'label_select_1':'가죽',
               'label_select_2':'페인트',
               'label_select_3':'계피',
               'label_select_4':'레몬',
               'sound':'train_id_02_03',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)
               
               {'layout_type':'choice_0',
               'img_bg':'bg_s_02_03',
               'img_btn1':'레몬에이드50',
               'img_btn2':'레몬에이드100',
               'img_btn3':'레몬에이드200',
               'img_btn4':'레몬',
               'head_title':'Farm',
               'body_text':'레몬 1개를 가지고,\n음료 5잔을 만들 수 있습니다.',
               'label_select_1':'50잔',
               'label_select_2':'100잔',
               'label_select_3':'200잔',
               'label_select_4':'',
               'sound':'train_id_02_04',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)},
               
               {'layout_type':'choice_3',
               'img_bg':'bg_s_02_03',
               'img_btn1':'레몬에이드50',
               'img_btn2':'레몬에이드100',
               'img_btn3':'레몬에이드200',
               'img_btn4':'레몬',
               'head_title':'Farm',
               'body_text':'레몬이 20개 있다면,\n음료를 몇 잔 만들 수 있을까요?',
               'label_select_1':'20잔',
               'label_select_2':'50잔',
               'label_select_3':'100잔',
               'label_select_4':'',
               'sound':'train_id_02_05',
               'scent':0},
               
               {'layout_type':'choice_1',
               'img_bg':'bg_s_02_03',
               'img_btn1':'레몬에이드100',
               'img_btn2':'레몬에이드100',
               'img_btn3':'레몬에이드100',
               'img_btn4':'레몬에이드100',
               'head_title':'Farm',
               'body_text':'수고하셨습니다.\n감사합니다.',
               'label_select_1':'100잔',
               'label_select_2':'100잔',
               'label_select_3':'100잔',
               'label_select_4':'100잔',
               'sound':'train_id_thanks',
               'scent':0},
]

id_train_scene_3 = [{'layout_type':'choice_0',
               'img_bg':'bg_s_03_01',
               'img_btn1':'홍삼',
               'img_btn2':'수박',
               'img_btn3':'당근',
               'img_btn4':'땅콩',
               'head_title':'Farm',
               'body_text':'어떤 농장에 왔습니다.\n무엇을 재배하고 있는지 궁금합니다.',
               'label_select_1':'홍삼',
               'label_select_2':'수박',
               'label_select_3':'당근',
               'label_select_4':'땅콩',
               'sound':'train_id_03_01',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)
               
               {'layout_type':'choice_3',
               'img_bg':'bg_s_03_02',
               'img_btn1':'홍삼',
               'img_btn2':'수박',
               'img_btn3':'당근',
               'img_btn4':'땅콩',
               'head_title':'Farm',
               'body_text':'향을 느껴보시고 짐작해보세요.\n어떤 향을 느끼셨습니까?',
               'label_select_1':'홍삼',
               'label_select_2':'수박',
               'label_select_3':'당근',
               'label_select_4':'땅콩',
               'sound':'train_id_03_02',
               'answer_text':'홍삼',
               'scent':8},
               
               {'layout_type':'choice_0',
               'img_bg':'bg_s_03_03',
               'img_btn1':'210일',
               'img_btn2':'300일',
               'img_btn3':'420일',
               'img_btn4':'홍삼',
               'head_title':'Farm',
               'body_text':'기운이 없을 때 홍삼을 먹고 힘이 난 적이 있나요?\n경험을 서로 나눠보세요.',
               'label_select_1':'',
               'label_select_2':'',
               'label_select_3':'',
               'label_select_4':'',
               'sound':'train_id_03_03',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)},
               
               {'layout_type':'choice_0',
               'img_bg':'bg_s_03_04',
               'img_btn1':'210일',
               'img_btn2':'300일',
               'img_btn3':'420일',
               'img_btn4':'홍삼',
               'head_title':'Farm',
               'body_text':'부모님께 홍삼 선물을 드렸습니다.\n홍삼 엑기스 30병이 들어있습니다.',
               'label_select_1':'210일',
               'label_select_2':'300일',
               'label_select_3':'420일',
               'label_select_4':'',
               'sound':'train_id_03_04',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)},
               
               {'layout_type':'choice_3',
               'img_bg':'bg_s_03_04',
               'img_btn1':'210일',
               'img_btn2':'300일',
               'img_btn3':'420일',
               'img_btn4':'양파',
               'head_title':'Farm',
               'body_text':'홍삼 엑기스 1병을 일주일동안 나눠먹는다면,\n며칠동안 전부 복용할 수 있을까요?',
               'label_select_1':'210일',
               'label_select_2':'300일',
               'label_select_3':'420일',
               'label_select_4':'',
               'sound':'train_id_03_05',
               'scent':0},
               
               {'layout_type':'choice_1',
               'img_bg':'bg_s_03_03',
               'img_btn1':'210일',
               'img_btn2':'210일',
               'img_btn3':'210일',
               'img_btn4':'210일',
               'head_title':'Farm',
               'body_text':'수고하셨습니다.\n감사합니다.',
               'img_btn3':'돈20000',
               'label_select_1':'210일',
               'label_select_2':'210일',
               'label_select_3':'210일',
               'label_select_4':'210일',
               'sound':'train_id_thanks',
               'scent':0},
]

id_train_scene_4 = [{'layout_type':'choice_0',
               'img_bg':'bg_s_04_01',
               'img_btn1':'꿀',
               'img_btn2':'허브',
               'img_btn3':'메론',
               'img_btn4':'고구마',
               'head_title':'Farm',
               'body_text':'풀이 무성한 숲에 왔습니다.\n어떤 향이 정신을 일깨워줍니다.',
               'label_select_1':'꿀',
               'label_select_2':'허브',
               'label_select_3':'메론',
               'label_select_4':'고구마',
               'sound':'train_id_04_01',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)
               
               {'layout_type':'choice_3',
               'img_bg':'bg_s_04_01',
               'img_btn1':'꿀',
               'img_btn2':'허브',
               'img_btn3':'메론',
               'img_btn4':'고구마',
               'head_title':'Farm',
               'body_text':'향을 느껴보시고 짐작해보세요.\n어떤 향을 느끼셨습니까?',
               'label_select_1':'꿀',
               'label_select_2':'허브',
               'label_select_3':'메론',
               'label_select_4':'고구마',
               'sound':'train_id_04_02',
               'answer_text':'허브',
               'scent':4},
               
               {'layout_type':'choice_0',
               'img_bg':'bg_s_04_02',
               'img_btn1':'허브',
               'img_btn2':'로즈마리',
               'img_btn3':'쑥',
               'img_btn4':'양파',
               'head_title':'Farm',
               'body_text':'허브는 기분을 상쾌하게 하고 정신을 회복시킵니다.\n대표적으로 로즈마리, 라벤더, 유칼립투스, 바질을 사용합니다.',
               'label_select_1':'',
               'label_select_2':'',
               'label_select_3':'',
               'label_select_4':'',
               'sound':'train_id_04_03',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)},
               
               {'layout_type':'choice_0',
               'img_bg':'bg_s_04_03',
               'img_btn1':'허브',
               'img_btn2':'로즈마리',
               'img_btn3':'쑥',
               'img_btn4':'양파',
               'head_title':'Farm',
               'body_text':'허브 차를 구매하러 마트에 왔습니다.\n직원이 몇가지 제품을 추천해주었습니다.',
               'label_select_1':'유칼립투스',
               'label_select_2':'로즈마리',
               'label_select_3':'쑥',
               'label_select_4':'',
               'sound':'train_id_04_04',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)},
               
               {'layout_type':'choice_3',
               'img_bg':'bg_s_04_03',
               'img_btn1':'허브',
               'img_btn2':'로즈마리',
               'img_btn3':'쑥',
               'img_btn4':'양파',
               'head_title':'Farm',
               'body_text':'아래 재료들을 살펴보세요.\n대표적인 허브차가 아닌 것은 무엇일까요?',
               'label_select_1':'유칼립투스',
               'label_select_2':'로즈마리',
               'label_select_3':'쑥',
               'label_select_4':'',
               'sound':'train_id_04_05',
               'scent':0},
               
               {'layout_type':'choice_1',
               'img_bg':'bg_s_04_03',
               'img_btn1':'쑥',
               'img_btn2':'쑥',
               'img_btn3':'쑥',
               'img_btn4':'쑥',
               'head_title':'Farm',
               'body_text':'수고하셨습니다.\n감사합니다.',
               'label_select_1':'쑥',
               'label_select_2':'쑥',
               'label_select_3':'쑥',
               'label_select_4':'쑥',
               'sound':'train_id_thanks',
               'scent':0},
]

id_train_scene_5 = [{'layout_type':'choice_0',
               'img_bg':'basic',
               'img_btn1':'정답',
               'img_btn2':'오답',
               'img_btn3':'정답',
               'img_btn4':'오답',
               'head_title':'Farm',
               'body_text':'지금까지 4문항을 진행해보았습니다.\n이전 문항에서 느껴본 향을 기억해보세요.',
               'label_select_1':'맞다.',
               'label_select_2':'아니다.',
               'label_select_3':'맞다.',
               'label_select_4':'아니다.',
               'sound':'train_id_05_01',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)
               
               {'layout_type':'choice_2',
               'img_bg':'basic',
               'img_btn1':'정답',
               'img_btn2':'오답',
               'img_btn3':'정답',
               'img_btn4':'오답',
               'head_title':'Farm',
               'body_text':'향을 느껴보세요.\n이전 문항에서 느껴보신 향이 맞나요?',
               'label_select_1':'맞다.',
               'label_select_2':'아니다.',
               'label_select_3':'맞다.',
               'label_select_4':'아니다.',
               'sound':'train_id_05_02',
               'answer_text':'아니다',
               'scent':5},
               
               {'layout_type':'choice_1',
               'img_bg':'bg_s_05_02',
               'img_btn1':'오답',
               'img_btn2':'오답',
               'img_btn3':'오답',
               'img_btn4':'오답',
               'head_title':'Farm',
               'body_text':'복숭아 향이었습니다.\n지나간 향을 기억해보는 것은 인지 활동에 도움을 줍니다.',
               'label_select_1':'아니다.',
               'label_select_2':'아니다.',
               'label_select_3':'아니다.',
               'label_select_4':'아니다.',
               'sound':'train_id_05_03',
               'scent':0},
               
               {'layout_type':'choice_0',
               'img_bg':'bg_s_05_02',
               'head_title':'Farm',
               'body_text':'수고하셨습니다.\n감사합니다.',
               'label_select_1':'맞다.',
               'label_select_2':'아니다.',
               'label_select_3':'맞다.',
               'label_select_4':'아니다.',
               'sound':'train_id_thanks',
               'scent':0},
]

id_train_scene_6 = [{'layout_type':'choice_0',
               'img_bg':'bg_s_06_01',
               'img_btn1':'커피',
               'img_btn2':'사과',
               'img_btn3':'오렌지',
               'img_btn4':'생강',
               'head_title':'Farm',
               'body_text':'길을 걷고 있습니다.\n길가의 어떤 매장으로부터 향이 느껴집니다.',
               'label_select_1':'커피',
               'label_select_2':'사과',
               'label_select_3':'오렌지',
               'label_select_4':'생강',
               'sound':'train_id_06_01',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)
               
               {'layout_type':'choice_3',
               'img_bg':'bg_s_06_01',
               'img_btn1':'커피',
               'img_btn2':'사과',
               'img_btn3':'오렌지',
               'img_btn4':'생강',
               'head_title':'Farm',
               'body_text':'향을 느껴보시고 짐작해보세요.\n어떤 향을 느끼셨습니까?',
               'label_select_1':'커피',
               'label_select_2':'사과',
               'label_select_3':'오렌지',
               'label_select_4':'생강',
               'sound':'train_id_06_02',
               'answer_text':'커피',
               'scent':6},
               
               {'layout_type':'choice_0',
               'img_bg':'bg_s_06_02',
               'img_btn1':'20배',
               'img_btn2':'50배',
               'img_btn3':'100배',
               'img_btn4':'커피',
               'head_title':'Farm',
               'body_text':'70년대 커피 한잔 가격은 80원이었습니다.\n커피를 처음 마셨던 경험을 서로 나눠보세요.',
               'label_select_1':'',
               'label_select_2':'',
               'label_select_3':'',
               'label_select_4':'',
               'sound':'train_id_06_03',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)},
               
               {'layout_type':'choice_0',
               'img_bg':'bg_s_06_03',
               'img_btn1':'20배',
               'img_btn2':'50배',
               'img_btn3':'100배',
               'img_btn4':'커피',
               'head_title':'Farm',
               'body_text':'시원한 커피를 마시기 위해 카페에 갔습니다.\n커피 가격이 많이 올랐습니다.',
               'label_select_1':'20배',
               'label_select_2':'50배',
               'label_select_3':'100배',
               'label_select_4':'',
               'sound':'train_id_06_04',
               'scent':0},
               
               {'layout_type':'choice_3',
               'img_bg':'bg_s_06_03',
               'img_btn1':'20배',
               'img_btn2':'50배',
               'img_btn3':'100배',
               'img_btn4':'커피',
               'head_title':'Farm',
               'body_text':'커피 한잔이 4,000원입니다.\n70년대와 비교해서 몇배 상승한 것일까요?',
               'label_select_1':'20배',
               'label_select_2':'50배',
               'label_select_3':'100배',
               'label_select_4':'',
               'sound':'train_id_06_05',
               'scent':0},
               
               {'layout_type':'choice_1',
               'img_bg':'bg_s_06_03',
               'img_btn1':'50배',
               'img_btn2':'50배',
               'img_btn3':'50배',
               'img_btn4':'50배',
               'head_title':'Farm',
               'body_text':'수고하셨습니다.\n감사합니다.',
               'label_select_1':'50배',
               'label_select_2':'50배',
               'label_select_3':'50배',
               'label_select_4':'50배',
               'sound':'train_id_thanks',
               'scent':0},
]

id_train_scene_7 = [{'layout_type':'choice_0',
               'img_bg':'bg_s_07_01',
               'img_btn1':'신문지',
               'img_btn2':'딸기',
               'img_btn3':'계란',
               'img_btn4':'후추',
               'head_title':'Farm',
               'body_text':'어떤 농장에 왔습니다.\n무엇을 재배하고 있는지 궁금합니다.',
               'label_select_1':'신문지',
               'label_select_2':'딸기',
               'label_select_3':'계란',
               'label_select_4':'후추',
               'sound':'train_id_07_01',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)
               
               {'layout_type':'choice_3',
               'img_bg':'bg_s_07_01',
               'img_btn1':'신문지',
               'img_btn2':'딸기',
               'img_btn3':'계란',
               'img_btn4':'후추',
               'head_title':'Farm',
               'body_text':'향을 느껴보시고 짐작해보세요.\n어떤 향을 느끼셨습니까?',
               'label_select_1':'신문지',
               'label_select_2':'딸기',
               'label_select_3':'계란',
               'label_select_4':'후추',
               'sound':'train_id_07_02',
               'answer_text':'딸기',
               'scent':7},
    
               {'layout_type':'choice_0',
               'img_bg':'bg_s_07_02',
               'img_btn1':'1.5kg',
               'img_btn2':'3.0kg',
               'img_btn3':'4.5kg',
               'img_btn4':'딸기',
               'head_title':'Farm',
               'body_text':'진짜 딸기의 제철은 5~6월입니다.\n시설에서 재배되면서 겨울에 많이 나오게 되었습니다.',
               'label_select_1':'1.5kg',
               'label_select_2':'3.0kg',
               'label_select_3':'4.5kg',
               'label_select_4':'',
               'sound':'train_id_07_03',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)},
               
               {'layout_type':'choice_0',
               'img_bg':'bg_s_07_03',
               'img_btn1':'1.5kg',
               'img_btn2':'3.0kg',
               'img_btn3':'4.5kg',
               'img_btn4':'딸기',
               'head_title':'Farm',
               'body_text':'아이들에게 맛있는 딸기 3팩을 사주었습니다.\n1팩에 딸기 1.5Kg이 들어있습니다.',
               'label_select_1':'1.5kg',
               'label_select_2':'3.0kg',
               'label_select_3':'4.5kg',
               'label_select_4':'',
               'sound':'train_id_07_04',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)},
               
               {'layout_type':'choice_3',
               'img_bg':'bg_s_07_03',
               'img_btn1':'1.5kg',
               'img_btn2':'3.0kg',
               'img_btn3':'4.5kg',
               'img_btn4':'딸기',
               'head_title':'Farm',
               'body_text':'아이들이 딸기를 1팩만 먹었습니다.\n딸기 몇 Kg이 남았을까요?',
               'label_select_1':'1.5kg',
               'label_select_2':'3.0kg',
               'label_select_3':'4.5kg',
               'label_select_4':'',
               'sound':'train_id_07_05',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)},
               
               {'layout_type':'choice_1',
               'img_bg':'bg_s_07_03',
               'img_btn1':'3.0kg',
               'img_btn2':'3.0kg',
               'img_btn3':'3.0kg',
               'img_btn4':'3.0kg',
               'head_title':'Farm',
               'body_text':'수고하셨습니다.\n감사합니다.',
               'label_select_1':'3.0kg',
               'label_select_2':'3.0kg',
               'label_select_3':'3.0kg',
               'label_select_4':'3.0kg',
               'sound':'train_id_thanks',
               'scent':0},
]

id_train_scene_8 = [{'layout_type':'choice_0',
               'img_bg':'bg_s_08_01',
               'img_btn1':'숯불고기',
               'img_btn2':'마늘',
               'img_btn3':'초콜릿',
               'img_btn4':'포도',
               'head_title':'Farm',
               'body_text':'추운 겨울에 신나게 놀고 집에 왔습니다.\n몸과 마음을 녹여주는 것이 있습니다.',
               'label_select_1':'숯불고기',
               'label_select_2':'마늘',
               'label_select_3':'초콜릿',
               'label_select_4':'포도',
               'sound':'train_id_08_01',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)
               
               {'layout_type':'choice_3',
               'img_bg':'bg_s_08_02',
               'img_btn1':'숯불고기',
               'img_btn2':'마늘',
               'img_btn3':'초콜릿',
               'img_btn4':'포도',
               'head_title':'Farm',
               'body_text':'향을 느껴보시고 짐작해보세요.\n어떤 향을 느끼셨습니까?',
               'label_select_1':'숯불고기',
               'label_select_2':'마늘',
               'label_select_3':'초콜릿',
               'label_select_4':'포도',
               'sound':'train_id_08_02',
               'answer_text':'초콜릿',
               'scent':2},
               
               {'layout_type':'choice_0',
               'img_bg':'bg_s_08_03',
               'img_btn1':'숯불고기',
               'img_btn2':'마늘',
               'img_btn3':'초콜릿',
               'img_btn4':'포도',
               'head_title':'Farm',
               'body_text':'옛날 슈퍼마켓에는 여러 초콜릿 제품이 있었습니다.\n경험을 서로 나눠보세요.',
               'label_select_1':'숯불고기',
               'label_select_2':'마늘',
               'label_select_3':'초콜릿',
               'label_select_4':'포도',
               'sound':'train_id_08_03',
               'scent':0}, # 카트리지 번호 (0보다 크면 발향)},
               
               {'layout_type':'choice_0',
               'img_bg':'bg_s_08_03',
               'img_btn1':'숯불고기',
               'img_btn2':'마늘',
               'img_btn3':'초콜릿',
               'img_btn4':'포도',
               'head_title':'Farm',
               'body_text':'수고하셨습니다.\n감사합니다.',
               'label_select_1':'초콜릿',
               'label_select_2':'초콜릿',
               'label_select_3':'초콜릿',
               'label_select_4':'초콜릿',
               'sound':'train_id_thanks',
               'scent':0},
]

_all_train_scenes = [
    id_train_scene_1, id_train_scene_2, id_train_scene_3, id_train_scene_4,
    id_train_scene_5, id_train_scene_6, id_train_scene_7, id_train_scene_8
]

for scene in _all_train_scenes:
    for step in scene:
        randomize_scent_choice_step(step, use_extra_decoys=True)